#!/bin/bash
clear
read -p "VM Name: " dis_0
read -p "Cpu Cores: " core_0
read -p "Ram Size: " ram_0
read -p "Disk Size: " disk_0
clear
echo "---CHOOSE AN ISO---"
prompt="Please select a file:"
options=( $(find ~ -type f -name '*.iso'; find ~ -type f -name '*.img') )

PS3="$prompt "
select opt in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
       #echo  "You picked $opt which is file $REPLY"
        break

    else
        echo "Invalid option. Try another one."
    fi
done    


ls -ld "$opt"


qemu-img create -f qcow2 ~/.config/vm-mgr/$dis_0.qcow2 $disk_0


echo -e "\e[33mConfig Done!\e[0m"
sleep 0.7
clear
echo "Staring $dis_0 in"
echo "3"
sleep 0.8
echo "2"
sleep 0.8
echo "1"

qemu-system-x86_64 -enable-kvm -m $ram_0 -smp $core_0 -hda ~/.config/vm-mgr/$dis_0.qcow2 -boot d -cdrom $opt -netdev user,id=net0,net=192.168.0.0/24,dhcpstart=192.168.0.9 -device virtio-net-pci,netdev=net0 -vga qxl -device AC97 &
disown
exit 0
