#!/bin/bash
clear
echo "---Choose a vm to delete---"
prompt="VM:"
options=( $(ls -1 ~/.config/vm-mgr/* | sed s/^.*\\/\// | sed 's/.qcow2//g') )


PS3="$prompt "
select opt in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        #echo  "You picked $opt which is file $REPLY"
        break

    else
        echo "Invalid option. Try another one."
    fi
done 


rm -rf ~/.config/vm-mgr/$opt.qcow2

echo -e "\e[31m$opt was deleted\e[0m"
exit 0
