#!/bin/bash
clear
echo "---CHOOSE A VM---"
prompt="Please select a file:"
options=( $(ls -1 ~/.config/qemu-vms/* | sed s/^.*\\/\// | sed 's/.qcow2//g') )


PS3="$prompt "
select opt in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        echo  "You picked $opt which is file $REPLY"
        break

    else
        echo "Invalid option. Try another one."
    fi
done    


rm -rf ~/.config/qemu-vms/$opt.qcow2

echo -e "\e[31m$opt was deleted\e[0m"
