#!/bin/bash
clear
echo -e "
Type the number next to the option you want to execute, so to start a VM type "1"

All Virtual Machine(VM) disks are stored in ~/.config/vm-manager/

1) Start a VM - start an already created vm.
2) Create a VM - Make a VM install the OS from the img then start the vm from vm-manager and the "Start a VM" option.
3) Delete a VM - delete any VM.
"
