#!/bin/bash
clear
echo -e "
Type the number next to the option you want to execute, so to start a VM type "1"

We recomend to do set threads to about half of $(nproc)

When setting memory or disk sizes please end the size with "M" (for megabyte) or "G" (gigabyte). 
So when setting disk size do 4G or 4000M (same applies to ram!) 

All Virtual Machine(VM) disks are stored in ~/.config/vm-mgr/

1) Start a VM - start an already created vm.
2) Create a VM - Make a VM install the OS from the img then start the vm from vm-manager and the "Start a VM" option.
3) Delete a VM - delete any VM.
"
