#!/bin/bash
chmod +x *
PS3='Please choose an OS: '
options=("FreeBSD(bhyve)" "NetBSD(NVMM)" "Linux(KVM)" "Quit")
select opt in "${options[@]}"
do
    case $opt in
	"FreeBSD(bhyve)")
            ./install-freebsd; break  
            ;;
        "NetBSD(NVMM)")
            ./install-netbsd; break
            ;;
        "Linux(KVM)")
            ./install-linux; break
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done

cd ../; rm -rf vm-mgr
exit 0
