#!/bin/bash
clear

echo "---CHOOSE A VM---"
prompt="VM:"
options=( $(ls -1 ~/.config/vm-mgr/* | sed s/^.*\\/\// | sed 's/.qcow2//g') )


PS3="$prompt "
select opt in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        #echo  "You picked $opt which is file $REPLY"
        break

    else
        echo "Invalid option. Try another one."
    fi
done    


clear



read -p "Threads: " core_0
read -p "Memory: " ram_0


qemu-system-x86_64 -enable-kvm -m $ram_0 -smp $core_0 -hda ~/.config/vm-mgr/$opt.qcow2 -boot d -netdev user,id=net0,net=192.168.0.0/24,dhcpstart=192.168.0.9 -device virtio-net-pci,netdev=net0 -vga qxl -device AC97 &

exit 0
clear

